#!/usr/bin/env python3
"""Pair two panels' measurements of the SAME nominal patches, for a direct
panel-to-panel comparison rather than each panel's separate request-vs-measured
error.

Both the F7 and Huessen campaigns were generated by color_campaign_spec.py with
the same seed and gamut-steps, so their patch uids and requested RGBs coincide
wherever the plans overlap — this is not a coincidence to route around, it is
what makes a genuine paired comparison possible: for a shared uid, "what colour
did panel A produce" and "what colour did panel B produce" are answers to the
exact same question, not answers from two different questions that merely look
similar.

Output pairs three points per shared, measured uid: the request (identical for
both, by construction), and each panel's actual measured result. The number
that matters here is NOT either panel's distance from the request — that is
already covered by color_lut_export.py — it is the distance BETWEEN the two
panels' results, which is the direct answer to "how much does it matter which
of these two screens a given image lands on".
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from color_lut_export import srgb_to_xyz_pct
from color_model import delta_e76, lab, load_records, primaries, xyz_to_srgb8


def measured_by_uid(records: list[dict]) -> dict[str, dict]:
    out = {}
    for r in records:
        uid = r.get("uid")
        if uid and "xyz_d65_pct" in r and r.get("rgb"):
            out[uid] = r
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-a", type=pathlib.Path, required=True, help="panel A's campaign.jsonl")
    ap.add_argument("--data-b", type=pathlib.Path, required=True, help="panel B's campaign.jsonl")
    ap.add_argument("--label-a", default="A")
    ap.add_argument("--label-b", default="B")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    args = ap.parse_args(argv)

    recs_a = load_records(args.data_a)
    recs_b = load_records(args.data_b)
    by_a = measured_by_uid(recs_a)
    by_b = measured_by_uid(recs_b)

    shared = sorted(set(by_a) & set(by_b))
    if not shared:
        print("! no shared, measured uids between the two datasets — nothing to compare")
        return 1

    prim_a = primaries(recs_a)
    prim_b = primaries(recs_b)
    # Per-panel adaptation: rescale that panel's OWN measurement so ITS OWN
    # paper white reads as reference white. Using one panel's white to adapt
    # the other's readings would silently make the comparison about which
    # panel is closer to panel A's paper, not about the panels themselves.
    scale_a = prim_a["white"]["xyz"] / srgb_to_xyz_pct(np.array([255, 255, 255]))
    scale_b = prim_b["white"]["xyz"] / srgb_to_xyz_pct(np.array([255, 255, 255]))

    pairs = []
    des_between = []
    for uid in shared:
        ra, rb = by_a[uid], by_b[uid]
        rgb = ra["rgb"]
        if tuple(rgb) != tuple(rb["rgb"]):
            continue  # same uid, different request text — a spec drift, skip rather than mislabel
        want_xyz = srgb_to_xyz_pct(np.array(rgb))
        xyz_a, xyz_b = np.array(ra["xyz_d65_pct"]), np.array(rb["xyz_d65_pct"])
        lab_a, lab_b = lab(xyz_a / scale_a), lab(xyz_b / scale_b)
        de = delta_e76(lab_a, lab_b)
        des_between.append(de)
        pairs.append(
            {
                "uid": uid,
                "rgb": [int(c) for c in rgb],
                "want": [round(float(x), 2) for x in lab(want_xyz)],
                "a": [round(float(x), 2) for x in lab_a],
                "b": [round(float(x), 2) for x in lab_b],
                # Display swatches for each panel's ACTUAL measured colour (not
                # the shared request) — adapted per-panel so paper white reads
                # as screen white, same reasoning as the per-panel Lab
                # adaptation above. Without this both point clouds would
                # render in the identical requested colour and the whole
                # point of a two-panel comparison — seeing what each screen
                # actually did — would be invisible.
                "a_rgb": list(xyz_to_srgb8(xyz_a / scale_a)),
                "b_rgb": list(xyz_to_srgb8(xyz_b / scale_b)),
                "de_between": round(float(de), 3),
                "phase": ra.get("phase"),
            }
        )

    inks_a = {n: {"lab": [round(float(x), 2) for x in lab(prim_a[n]["xyz"])]} for n in prim_a}
    inks_b = {n: {"lab": [round(float(x), 2) for x in lab(prim_b[n]["xyz"])]} for n in prim_b}

    payload = {
        "label_a": args.label_a,
        "label_b": args.label_b,
        "pairs": pairs,
        "inks_a": inks_a,
        "inks_b": inks_b,
        "white_lab_a": [round(float(x), 2) for x in lab(prim_a["white"]["xyz"])],
        "white_lab_b": [round(float(x), 2) for x in lab(prim_b["white"]["xyz"])],
        "black_lab_a": [round(float(x), 2) for x in lab(prim_a["black"]["xyz"])],
        "black_lab_b": [round(float(x), 2) for x in lab(prim_b["black"]["xyz"])],
    }
    args.out.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")

    de = np.array(des_between)
    print(f"{len(pairs)} shared patches -> {args.out}")
    print(
        f"  panel-to-panel dE76: mean {de.mean():.2f}  median {np.median(de):.2f}  p95 {np.percentile(de, 95):.2f}  worst {de.max():.2f}"
    )
    by_phase = collections.defaultdict(list)
    for p in pairs:
        by_phase[p["phase"]].append(p["de_between"])
    print("  by phase:")
    for k, v in sorted(by_phase.items(), key=lambda kv: -np.mean(kv[1])):
        print(f"    {k or '(none)':16s} n={len(v):4d}  mean {np.mean(v):.2f}  worst {max(v):.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
