name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -e "webserver/[test]"

      - name: Run tests
        run: pytest -m "not time_intensive"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            fakeroot \
            dpkg-dev \
            debhelper
            
      - name: Build Debian packages
        run: |
          chmod +x webserver/build-deb.sh
          ./webserver/build-deb.sh

      - name: Show generated packages
        run: |
          find . -name "*.deb" -print
